### ISSUE TITLE
紧急，PaddleSeg中的OCRNet模型导出为onnx，推理失败

### ISSUE THREAD

**Issue by diyaxxxx** [PaddlePaddle/Paddle2ONNX#1225]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
[E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=autodl-container-f4d5458449-011211ac ; expr=cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data); 
2024-04-11 00:36:36.778269454 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running FusedConv node. Name:'p2o.Conv.34_p2o.Add.26_p2o.Relu.33' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    ort_outs = ort_session.run(None, ort_inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'p2o.Conv.34_p2o.Add.26_p2o.Relu.33' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)

**更多信息 :**
 - 用于部署的推理引擎:onnxruntime
 - 为什么需要转换为ONNX格式：需要应用到pytorch环境中
 - Paddle2ONNX版本:1.10.0
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/138844388/d4527be1-6157-42b1-828d-d7e47a683815)

**其他信息**
使用paddle模型进行GPU推理可以成功
转为onnx后调用CUDA推理失败
已经通过语句python tools/export.py --config  my.yml --model_path ../autodl-tmp/output/best_model/model.pdparams --input_shape 1 3 480 640固定paddle模型的输入形状

**Comment by Jiang-Jia-Jun** [comment]
这个问题先前看到反馈过多次。 使用ONNX Runtime CPU应该可以推理，使用ONNX Runtime GPU且关闭图优化也可以推理。 可以自行再测试下，可能得在ONNX Runtime仓库下提问

**Comment by diyaxxxx** [comment]
> 这个问题先前看到反馈过多次。 使用ONNX Runtime CPU应该可以推理，使用ONNX Runtime GPU且关闭图优化也可以推理。 可以自行再测试下，可能得在ONNX Runtime仓库下提问

感谢回复。
onnx在CPU上是可以推理的，目前的需求是在GPU上推理
根据sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_DISABLE_ALL关闭图优化
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/138844388/bb588510-3e21-4773-9834-de55a0bf774d)

关闭图优化后，onnx在CPU上推理失败
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/138844388/7d0fdf70-e95d-4100-82a2-1491e84bcc6d)

在GPU上推理失败
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/138844388/5e8b4a1f-d8ce-41ec-a35f-5acf385faff8)

**Comment by Zheng-Bicheng** [comment]
CPU能推理GPU不能推理看上去像是ONNXRuntime自身的问题呀

**Comment by diyaxxxx** [comment]
> CPU能推理GPU不能推理看上去像是ONNXRuntime自身的问题呀

换过几个onnxruntime版本都会有相同的错误

**Comment by Zheng-Bicheng** [comment]
> 换过几个onnxruntime版本都会有相同的错误

我的理解是，CPU能推理说明模型本身没问题。至于你说的ONNXRuntime换了几个版本都不行，是不是把模型提交到ONNXRuntime的Issues让他们帮忙看下呢？

**Comment by diyaxxxx** [comment]
好的谢谢，已经提交了

**Comment by diyaxxxx** [comment]
> > 换过几个onnxruntime版本都会有相同的错误
> 
> 我的理解是，CPU能推理说明模型本身没问题。至于你说的ONNXRuntime换了几个版本都不行，是不是把模型提交到ONNXRuntime的Issues让他们帮忙看下呢？

好的，谢谢，已经提交了

**Comment by diyaxxxx** [comment]
> 这个问题先前看到反馈过多次。 使用ONNX Runtime CPU应该可以推理，使用ONNX Runtime GPU且关闭图优化也可以推理。 可以自行再测试下，可能得在ONNX Runtime仓库下提问

感谢！问题解决！关闭图优化之后在GPU上推理成功，之前的测试代码不正确，导致仍然报错，测试成功代码如下：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/138844388/38e88bd6-fb58-4489-931c-354a16a04061)
